services:

  traefik:
      image: docker.io/library/traefik:v2.11.2
      container_name: traefik
      restart: unless-stopped
      ipc: none
      read_only: true
      environment:
        BROADSEA_HOST: ${BROADSEA_HOST}
      labels:
      - "traefik.enable=true"
      ports:
        - "80:80"
        - "443:443"
      volumes:
        - ./traefik/traefik_${HTTP_TYPE}.yml:/etc/traefik/traefik.yml:ro
        - ./traefik/tls_${HTTP_TYPE}.yml:/etc/traefik/dynamic/tls.yml:ro
        - ./traefik/routers.yml:/etc/traefik/dynamic/routers.yml:ro
        - ${BROADSEA_CERTS_FOLDER}:/etc/certs:ro
        - /var/run/docker.sock:/var/run/docker.sock:ro

  ohdsi-webapi-3:
    container_name: ohdsi-webapi-3
    image: docker.io/ohdsi/webapi:latest
    platform: ${DOCKER_ARCH}
    restart: unless-stopped
    
    environment:
      CLASSPATH: ":/var/lib/ohdsi/webapi/lib/additional/broadsea_mounted.jar"
      DATASOURCE_DRIVERCLASSNAME: org.postgresql.Driver
      DATASOURCE_URL: ${WEBAPI_DATASOURCE_URL}
      DATASOURCE_USERNAME: ${WEBAPI_DATASOURCE_USERNAME}
      DATASOURCE_OHDSI_SCHEMA: ${WEBAPI_DATASOURCE_OHDSI_SCHEMA}
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
      SPRING_JPA_PROPERTIES_HIBERNATE_DEFAULT_SCHEMA: ${WEBAPI_DATASOURCE_OHDSI_SCHEMA}
      SPRING_BATCH_REPOSITORY_TABLEPREFIX: ${WEBAPI_DATASOURCE_OHDSI_SCHEMA}.BATCH_
      FLYWAY_DATASOURCE_DRIVERCLASSNAME: org.postgresql.Driver
      FLYWAY_DATASOURCE_URL: ${WEBAPI_DATASOURCE_URL}
      FLYWAY_DATASOURCE_USERNAME: ${WEBAPI_DATASOURCE_USERNAME}
      FLYWAY_LOCATIONS: classpath:db/migration/postgresql
      FLYWAY_PLACEHOLDERS_OHDSISCHEMA: ${WEBAPI_DATASOURCE_OHDSI_SCHEMA}
      FLYWAY_SCHEMAS: ${WEBAPI_DATASOURCE_OHDSI_SCHEMA}
      FLYWAY_BASELINE_ON_MIGRATE: ${FLYWAY_BASELINE_ON_MIGRATE}
      FLYWAY_TABLE: schema_history
      flyway_baselineVersionAsString: "2.2.5.20180212152023"  # this env var is case sensitive
      FLYWAY_BASELINEDESCRIPTION: Base Migration
      SECURITY_CORS_ENABLED: "true"
      SECURITY_ORIGIN: "${HTTP_TYPE}://${BROADSEA_HOST}"
      SOLR_ENDPOINT: "${SOLR_VOCAB_ENDPOINT}"

      # Security provider enabling/disabling
      
      SECURITY_PROVIDER: ${WEBAPI_SECURITY_PROVIDER}
      SECURITY_TOKEN_EXPIRATION: ${SECURITY_TOKEN_EXPIRATION}
      SECURITY_AUTH_KERBEROS_ENABLED: ${SECURITY_AUTH_KERBEROS_ENABLED}
      SECURITY_AUTH_OPENID_ENABLED: ${SECURITY_AUTH_OPENID_ENABLED}
      SECURITY_AUTH_FACEBOOK_ENABLED: ${SECURITY_AUTH_FACEBOOK_ENABLED}
      SECURITY_AUTH_GITHUB_ENABLED: ${SECURITY_AUTH_GITHUB_ENABLED}
      SECURITY_AUTH_GOOGLE_ENABLED: ${SECURITY_AUTH_GOOGLE_ENABLED}
      SECURITY_AUTH_JDBC_ENABLED: ${SECURITY_AUTH_JDBC_ENABLED}
      SECURITY_AUTH_LDAP_ENABLED: ${SECURITY_AUTH_LDAP_ENABLED}
      SECURITY_AUTH_AD_ENABLED: ${SECURITY_AUTH_AD_ENABLED}
      SECURITY_AUTH_CAS_ENABLED: ${SECURITY_AUTH_CAS_ENABLED}
      SECURITY_AUTH_GOOGLEIAP_ENABLED: ${SECURITY_AUTH_GOOGLEIAP_ENABLED}

      # Security env variables - Basic

      SECURITY_DB_DATASOURCE_SCHEMA: ${SECURITY_DB_DATASOURCE_SCHEMA}
      SECURITY_DB_DATASOURCE_URL: ${SECURITY_DB_DATASOURCE_URL}
      SECURITY_DB_DATASOURCE_DRIVERCLASSNAME: ${SECURITY_DB_DATASOURCE_DRIVERCLASSNAME}
      SECURITY_DB_DATASOURCE_USERNAME: ${SECURITY_DB_DATASOURCE_USERNAME}
      SECURITY_DB_DATASOURCE_AUTHENTICATIONQUERY: ${SECURITY_DB_DATASOURCE_AUTHENTICATIONQUERY}
      
      # Security env variables - LDAP

      SECURITY_LDAP_DN: ${SECURITY_LDAP_DN}
      SECURITY_LDAP_URL: ${SECURITY_LDAP_URL}
      SECURITY_LDAP_BASEDN: ${SECURITY_LDAP_BASEDN}
      SECURITY_LDAP_SYSTEM_USERNAME: ${SECURITY_LDAP_SYSTEM_USERNAME}
      SECURITY_LDAP_SEARCHSTRING: ${SECURITY_LDAP_SEARCHSTRING}
      SECURITY_LDAP_SEARCHBASE: ${SECURITY_LDAP_SEARCHBASE}

      # Security env variables - AD

      SECURITY_AD_URL: ${SECURITY_AD_URL}
      SECURITY_AD_SEARCHBASE: ${SECURITY_AD_SEARCHBASE}
      SECURITY_AD_SEARCHFILTER: ${SECURITY_AD_SEARCHFILTER}
      SECURITY_AD_PRINCIPALSUFFIX: ${SECURITY_AD_PRINCIPALSUFFIX}
      SECURITY_AD_SEARCHSTRING: ${SECURITY_AD_SEARCHSTRING}
      SECURITY_AD_USERMAPPING_DISPLAYNAMEATTR: ${SECURITY_AD_USERMAPPING_DISPLAYNAMEATTR}
      SECURITY_AD_USERMAPPING_USERNAMEATTR: ${SECURITY_AD_USERMAPPING_USERNAMEATTR}
      SECURITY_AD_SYSTEM_USERNAME: ${SECURITY_AD_SYSTEM_USERNAME}

      # Security env variables - Kerberos

      SECURITY_KERBEROS_SPN: ${SECURITY_KERBEROS_SPN}
      SECURITY_KERBEROS_KEYTABPATH: ${SECURITY_KERBEROS_KEYTABPATH}

      # Security env variables - OAuth

      SECURITY_OAUTH_CALLBACK_UI: ${SECURITY_OAUTH_CALLBACK_UI}
      SECURITY_OAUTH_CALLBACK_API: ${SECURITY_OAUTH_CALLBACK_API}
      SECURITY_OAUTH_CALLBACK_URLRESOLVER: ${SECURITY_OAUTH_CALLBACK_URLRESOLVER}
      SECURITY_OAUTH_GOOGLE_APIKEY: ${SECURITY_OAUTH_GOOGLE_APIKEY}
      SECURITY_OAUTH_FACEBOOK_APIKEY: ${SECURITY_OAUTH_FACEBOOK_APIKEY}
      SECURITY_OAUTH_GITHUB_APIKEY: ${SECURITY_OAUTH_GITHUB_APIKEY}


      # Security env variables - OpenID

      SECURITY_OID_CLIENTID: ${SECURITY_OID_CLIENTID}
      SECURITY_OID_APISECRET: ${SECURITY_OID_APISECRET}
      SECURITY_OID_URL: ${SECURITY_OID_URL}
      SECURITY_OID_LOGOUTURL: ${SECURITY_OID_LOGOUTURL}
      SECURITY_OID_EXTRASCOPES: ${SECURITY_OID_EXTRASCOPES}
      SECURITY_OID_REDIRECTURL: ${SECURITY_OID_REDIRECTURL}
      SECURITY_OID_CUSTOMPARAMS: ${SECURITY_OID_CUSTOMPARAMS}

      # Security env variables - IAP

      SECURITY_GOOGLEIAP_CLOUDPROJECTID: ${SECURITY_GOOGLEIAP_CLOUDPROJECTID}
      SECURITY_GOOGLEIAP_BACKENDSERVICEID: ${SECURITY_GOOGLEIAP_BACKENDSERVICEID}
      SECURITY_GOOGLE_ACCESSTOKEN_ENABLED: ${SECURITY_GOOGLE_ACCESSTOKEN_ENABLED}
      
      # Security env variables - CAS
      
      SECURITY_CAS_LOGINURL: ${HTTP_TYPE}://${WEBAPI_SECURITY_CAS_SERVER}/idp/profile/cas/login
      SECURITY_CAS_CALLBACKURL: ${HTTP_TYPE}://${BROADSEA_HOST}/WebAPI/user/cas/callback?client_name=CasClient
      SECURITY_CAS_SERVERURL: ${HTTP_TYPE}://${WEBAPI_SECURITY_CAS_SERVER}/idp/profile/cas
      SECURITY_CAS_CASTICKET: ticket

      # Security env variables - SAML

      SECURITY_SAML_ENTITYID: ${SECURITY_SAML_ENTITYID}
      SECURITY_SAML_IDPMETADATALOCATION: ${SECURITY_SAML_IDPMETADATALOCATION}
      SECURITY_SAML_KEYMANAGER_KEYSTOREFILE: ${SECURITY_SAML_KEYMANAGER_KEYSTOREFILE}
      SECURITY_SAML_KEYMANAGER_DEFAULTKEY: ${SECURITY_SAML_KEYMANAGER_DEFAULTKEY}
      SECURITY_SAML_METADATALOCATION: ${SECURITY_SAML_METADATALOCATION}
      SECURITY_SAML_CALLBACKURL: ${SECURITY_SAML_CALLBACKURL}
      SECURITY_SAML_SLOURL: ${SECURITY_SAML_SLOURL}
      SECURITY_SAML_MAXIMUMAUTHENTICATIONLIFETIME: ${SECURITY_SAML_MAXIMUMAUTHENTICATIONLIFETIME}

      # Atlas cohort caching

      CACHE_GENERATION_INVALIDAFTERDAYS: ${CACHE_GENERATION_INVALIDAFTERDAYS}
      CACHE_GENERATION_CLEANUPINTERVAL: ${CACHE_GENERATION_CLEANUPINTERVAL}

      # Multiple language support

      I18N_ENABLED: ${I18N_ENABLED}

      # Execution engine

      EXECUTIONENGINE_URL: ${EXECUTIONENGINE_URL}
      EXECUTIONENGINE_TOKEN: 
      EXECUTIONENGINE_UPDATESTATUSCALLBACK: "http://ohdsi-webapi:8080/WebAPI/executionservice/callbacks/submission/{id}/status/update/{password}"
      EXECUTIONENGINE_RESULTCALLBACK: "http://ohdsi-webapi:8080/WebAPI/executionservice/callbacks/submission/{id}/result/{password}"
      EXECUTION_INVALIDATION_MAXAGE_HOURS: 72
      EXECUTIONENGINE_RESULTEXCLUSIONS: "*.sqlite,covariates"


      # WebAPI logging levels
      LOGGING_LEVEL_ROOT: ${WEBAPI_LOGGING_LEVEL_ROOT}
      LOGGING_LEVEL_ORG_OHDSI: ${WEBAPI_LOGGING_LEVEL_ORG_OHDSI}
      LOGGING_LEVEL_ORG_APACHE_SHIRO: ${WEBAPI_LOGGING_LEVEL_ORG_APACHE_SHIRO}

    labels:
      - "traefik.enable=true"

    healthcheck:
      test: ["CMD-SHELL", "timeout 10s bash -c '</dev/tcp/localhost/8080' || exit 1"]
      timeout: 10s
      interval: 30s
      retries: 5
      start_period: 5m
  # Lightweight database initialization service
  db-populate:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      ohdsi-webapi-3:
        condition: service_healthy

    environment:
      SOURCE_NAME: ${SOURCE_NAME:-CDM Practice}
      SOURCE_KEY: ${SOURCE_KEY:-MY_CDM}
      SOURCE_DIALECT: ${SOURCE_DIALECT:-postgresql}
      CDM_SCHEMA: ${CDM_SCHEMA:-cdm}
      RESULTS_SCHEMA: ${RESULTS_SCHEMA:-results}
      VOCAB_SCHEMA: ${VOCAB_SCHEMA:-cdm}
      TEMP_SCHEMA: ${TEMP_SCHEMA:-temp_schema}
      SOURCE_CONNECTION: ${SOURCE_CONNECTION:-jdbc:postgresql://postgres-db:5432/xxxx?user=xxxx&password=xxxx}
      DB_HOST: ${DB_HOST:-localhost}
      DB_PORT: ${DB_PORT:-5432}
      DB_USER: ${DB_USER:-broadsea_user}
      DB_PASSWORD: ${DB_PASSWORD:-broadsea_password}
      DB_NAME: ${DB_NAME:-aml_report}
      WEBAPI_DATASOURCE_OHDSI_SCHEMA: ${WEBAPI_DATASOURCE_OHDSI_SCHEMA:-new_one_again}

    volumes:
      - ./scripts:/scripts

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h ${DB_HOST} -p ${DB_PORT} -U ${DB_USER} -d ${DB_NAME} || exit 1"]
      timeout: 10s
      interval: 10s
      retries: 5
      start_period: 10s

  ohdsi-atlas-3:
    container_name: ohdsi-atlas-3
    image: docker.io/ohdsi/atlas:latest
    platform: ${DOCKER_ARCH}
    restart: unless-stopped

    ipc: none
    privileged: false
    environment:
      WEBAPI_URL: ${BROADSEA_HOST}/WebAPI
      ATLAS_INSTANCE_NAME: ${ATLAS_INSTANCE_NAME}
      ATLAS_COHORT_COMPARISON_RESULTS_ENABLED: ${ATLAS_COHORT_COMPARISON_RESULTS_ENABLED}
      ATLAS_USER_AUTH_ENABLED: ${ATLAS_USER_AUTH_ENABLED}
      ATLAS_PLP_RESULTS_ENABLED: ${ATLAS_PLP_RESULTS_ENABLED}
      ATLAS_SECURITY_PROVIDER_NAME: ${ATLAS_SECURITY_PROVIDER_NAME}
      ATLAS_SECURITY_PROVIDER_TYPE: ${ATLAS_SECURITY_PROVIDER_TYPE}
      ATLAS_SECURITY_ICON: ${ATLAS_SECURITY_ICON}
      ATLAS_SECURITY_USE_FORM: ${ATLAS_SECURITY_USE_FORM}
      ATLAS_SECURITY_USE_AJAX: ${ATLAS_SECURITY_USE_AJAX}
      ATLAS_DISABLE_BROWSER_CHECK: ${ATLAS_DISABLE_BROWSER_CHECK}
      ATLAS_USE_EXECUTION_ENGINE: ${ATLAS_USE_EXECUTION_ENGINE}
      ATLAS_ENABLE_TAGGING_SECTION: ${ATLAS_ENABLE_TAGGING_SECTION}
      ATLAS_CACHE_SOURCES: ${ATLAS_CACHE_SOURCES}
      ATLAS_POLL_INTERVAL: ${ATLAS_POLL_INTERVAL}
      ATLAS_ENABLE_SKIP_LOGIN: ${ATLAS_ENABLE_SKIP_LOGIN}
      ATLAS_VIEW_PROFILE_DATES: ${ATLAS_VIEW_PROFILE_DATES}
      ATLAS_ENABLE_COSTS: ${ATLAS_ENABLE_COSTS}
      ATLAS_SUPPORT_URL: ${ATLAS_SUPPORT_URL}
      ATLAS_SUPPORT_MAIL: ${ATLAS_SUPPORT_MAIL}
      ATLAS_FEEDBACK_CONTACTS: ${ATLAS_FEEDBACK_CONTACTS}
      ATLAS_FEEDBACK_CUSTOM_HTML_TEMPLATE: ${ATLAS_FEEDBACK_CUSTOM_HTML_TEMPLATE}
      ATLAS_COMPANY_INFO_CUSTOM_HTML_TEMPLATE: ${ATLAS_COMPANY_INFO_CUSTOM_HTML_TEMPLATE}
      ATLAS_SHOW_COMPANY_INFO: ${ATLAS_SHOW_COMPANY_INFO}
      ATLAS_DEFAULT_LOCALE: ${ATLAS_DEFAULT_LOCALE}
      ATLAS_ENABLE_PERSON_COUNT: ${ATLAS_ENABLE_PERSON_COUNT}
      ATLAS_ENABLE_TERMS_AND_CONDITIONS: ${ATLAS_ENABLE_TERMS_AND_CONDITIONS}
    depends_on:
      ohdsi-webapi-3:
        condition: service_healthy
      db-populate:
        condition: service_completed_successfully
    labels:
      - "traefik.enable=true"
    
    volumes:
      - ./config/config-local-template.js:/tmp/config-local.js:ro
      - ./config/envsubst.sh:/tmp/envsubst.sh:ro
      - ./config/config-gis.js:/usr/share/nginx/html/atlas/js/config-gis.js:ro
    entrypoint: ["sh", "/tmp/envsubst.sh" ]

    healthcheck:
      test: ["CMD-SHELL", "timeout 10s bash -c '</dev/tcp/localhost/80' || exit 1"]
      timeout: 10s
      interval: 30s
      retries: 3
      start_period: 2m