
http:
  routers:

    traefik-dashboard:
      entryPoints: '{{ env "HTTP_TYPE" }}'
      service: api@internal
      rule: 'Host(`{{ env "BROADSEA_HOST" }}`) && PathPrefix(`/api`, `/dashboard`)'

    traefik:
      entryPoints: '{{ env "HTTP_TYPE" }}'
      service: "traefik"
      rule: 'Host(`{{ env "BROADSEA_HOST" }}`)'
     
    ohdsi-atlas-3:
      entryPoints: '{{ env "HTTP_TYPE" }}'
      service: "ohdsi-atlas-3"
      rule: 'Host(`{{ env "BROADSEA_HOST" }}`) && PathPrefix(`/atlas`)'

    ohdsi-webapi-3:
      entryPoints: '{{ env "HTTP_TYPE" }}'
      service: "ohdsi-webapi-3"
      rule: 'Host(`{{ env "BROADSEA_HOST" }}`) && PathPrefix(`/WebAPI`)'


  services:
    traefik:
      loadBalancer:
        servers:
          - url: http://traefik

    ohdsi-atlas-3:
      loadBalancer:
        servers:
          - url: http://ohdsi-atlas-3:8080

    ohdsi-webapi-3:
      loadBalancer:
        servers:
          - url: http://ohdsi-webapi-3:8080

    